// launcher/src/renderer/src/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import AppShell from "./AppShell.vue";
import type { LauncherSettings, LauncherSnapshot } from "../../shared/launcher-models";

type SectionId = "status" | "environment" | "diagnostics" | "settings";

const activeSection = ref<SectionId>("status");
const busyAction = ref<string | null>(null);
const editingSettings = ref(false);
const initializing = ref(true);
const desktopApi = window.rayleaLauncher;
const snapshot = ref<LauncherSnapshot>({
  settings: {
    serverExecutablePath: "",
    configPath: "",
    workdir: "",
    closeBehavior: "ask_every_time",
  },
  endpoint: {
    host: "127.0.0.1",
    port: 8080,
    baseUrl: "http://127.0.0.1:8080/",
  },
  environmentChecks: [],
  recentStderr: [],
  processId: null,
  serviceState: "stopped",
  shutdownRequested: false,
  serviceDetail: "正在加载启动器设置...",
  lastError: "",
  releaseCheck: {
    status: "unavailable",
    currentVersion: "",
    latestVersion: "",
    summary: "版本信息不可用",
    detail: "",
    releasePageUrl: "",
    updateAvailable: false,
  },
});
const settingsDraft = ref<LauncherSettings>({ ...snapshot.value.settings });
const controlsDisabled = computed(() => initializing.value || busyAction.value === "initialize");

const diagnosticsSummary = computed(() => {
  const checks = snapshot.value.environmentChecks
    .map((item) => `- ${item.title}：${item.summary}（${item.detail}${item.remediation ? `；${item.remediation}` : ""}）`)
    .join("\n");
  const recentErrors = snapshot.value.recentStderr.length ? snapshot.value.recentStderr.join("\n") : "当前没有新的错误输出。";
  return [`服务状态：${snapshot.value.serviceDetail}`, `服务入口：${snapshot.value.endpoint.baseUrl}`, "环境检查：", checks || "- 当前没有检查项。", "最近错误输出：", recentErrors].join("\n");
});

let unsubscribe: (() => void) | null = null;

function syncDraft(next: LauncherSnapshot) {
  snapshot.value = next;
  if (!editingSettings.value) {
    settingsDraft.value = { ...next.settings };
  }
}

function describeError(error: unknown, fallback: string) {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  return fallback;
}

async function runAction(action: string, task: () => Promise<void>) {
  busyAction.value = action;
  try {
    await task();
  } catch (error) {
    snapshot.value = {
      ...snapshot.value,
      lastError: describeError(error, "启动器操作失败。"),
      serviceDetail: action === "start" ? "启动服务失败。" : snapshot.value.serviceDetail,
    };
  } finally {
    busyAction.value = null;
  }
}

onMounted(async () => {
  unsubscribe = desktopApi.onSnapshot(syncDraft);
  busyAction.value = "initialize";
  try {
    await desktopApi.initialize();
    syncDraft(await desktopApi.getSnapshot());
  } catch (error) {
    snapshot.value = {
      ...snapshot.value,
      lastError: describeError(error, "启动器初始化失败。"),
      serviceDetail: "启动器初始化失败。",
    };
  } finally {
    busyAction.value = null;
    initializing.value = false;
  }
});

onBeforeUnmount(() => {
  unsubscribe?.();
});

async function saveSettings() {
  await runAction("save", async () => {
    await desktopApi.saveSettings(settingsDraft.value);
    editingSettings.value = false;
  });
}
</script>

<template>
  <AppShell
    :snapshot="snapshot"
    :active-section="activeSection"
    :settings-draft="settingsDraft"
    :editing-settings="editingSettings"
    :diagnostics-summary="diagnosticsSummary"
    :busy-action="busyAction"
    :controls-disabled="controlsDisabled"
    @navigate="activeSection = $event"
    @refresh="runAction('refresh', () => desktopApi.refresh())"
    @start="runAction('start', () => desktopApi.start())"
    @stop="runAction('stop', () => desktopApi.stop())"
    @open-web="runAction('open-web', () => desktopApi.openWebUi())"
    @open-release-page="runAction('open-release-page', () => desktopApi.openReleasePage())"
    @open-logs="runAction('open-logs', () => desktopApi.openLogsDirectory())"
    @begin-edit="editingSettings = true"
    @cancel-edit="
      editingSettings = false;
      settingsDraft = { ...snapshot.settings };
    "
    @save-settings="saveSettings"
    @update-settings="settingsDraft = $event"
    @choose-server="
      desktopApi.chooseServerExecutable().then((value: string | null) => {
        if (value) settingsDraft = { ...settingsDraft, serverExecutablePath: value };
      })
    "
    @choose-config="
      desktopApi.chooseConfigFile().then((value: string | null) => {
        if (value) settingsDraft = { ...settingsDraft, configPath: value };
      })
    "
    @choose-workdir="
      desktopApi.chooseWorkdir().then((value: string | null) => {
        if (value) settingsDraft = { ...settingsDraft, workdir: value };
      })
    "
    @exit="desktopApi.exitApplication()"
  />
</template>

// launcher/src/renderer/src/App.tsx
import { useState, useEffect, useMemo, useCallback } from "react";
import type { LauncherSettings, LauncherSnapshot } from "@shared/launcher-models";
import { AppShell } from "./AppShell";

type SectionId = "status" | "environment" | "diagnostics" | "settings";

const initialSnapshot: LauncherSnapshot = {
  settings: {
    serverExecutablePath: "",
    configPath: "",
    workdir: "",
    closeBehavior: "ask_every_time",
  },
  endpoint: {
    host: "127.0.0.1",
    port: 8080,
    baseUrl: "http://127.0.0.1:8080/",
  },
  environmentChecks: [],
  recentStderr: [],
  processId: null,
  serviceState: "stopped",
  shutdownRequested: false,
  serviceDetail: "正在加载启动器设置...",
  lastError: "",
  releaseCheck: {
    status: "unavailable",
    currentVersion: "",
    latestVersion: "",
    summary: "版本信息不可用",
    detail: "",
    releasePageUrl: "",
    updateAvailable: false,
  },
};

export function App() {
  const [activeSection, setActiveSection] = useState<SectionId>("status");
  const [busyAction, setBusyAction] = useState<string | null>(null);
  const [editingSettings, setEditingSettings] = useState(false);
  const [initializing, setInitializing] = useState(true);
  const [snapshot, setSnapshot] = useState<LauncherSnapshot>(initialSnapshot);
  // Local draft: only used during settings editing; mirrors what Vue's settingsDraft ref did
  const [editingDraft, setEditingDraft] = useState<LauncherSettings | null>(null);
  const [isMaximized, setIsMaximized] = useState(false);

  // settingsDraft = active editing draft when editing, else current settings from snapshot
  const settingsDraft = editingDraft ?? snapshot.settings;

  const controlsDisabled = useMemo(
    () => initializing || busyAction === "initialize",
    [initializing, busyAction],
  );

  const diagnosticsSummary = useMemo(() => {
    const checks = snapshot.environmentChecks
      .map(
        (item) =>
          `- ${item.title}：${item.summary}（${item.detail}${item.remediation ? `；${item.remediation}` : ""}）`,
      )
      .join("\n");
    const recentErrors =
      snapshot.recentStderr.length
        ? snapshot.recentStderr.join("\n")
        : "当前没有新的错误输出。";
    return [
      `服务状态：${snapshot.serviceDetail}`,
      `服务入口：${snapshot.endpoint.baseUrl}`,
      "环境检查：",
      checks || "- 当前没有检查项。",
      "最近错误输出：",
      recentErrors,
    ].join("\n");
  }, [snapshot]);

  // Sync snapshot updates into editing draft when not actively editing
  useEffect(() => {
    if (!editingSettings && editingDraft !== null) {
      setEditingDraft(null);
    }
  }, [snapshot.settings, editingSettings, editingDraft]);

  useEffect(() => {
    const unsub = window.rayleaLauncher.onSnapshot((next) => {
      setSnapshot(next);
    });
    setBusyAction("initialize");
    window.rayleaLauncher
      .initialize()
      .then(async () => {
        const snap = await window.rayleaLauncher.getSnapshot();
        setSnapshot(snap);
      })
      .catch((error: unknown) => {
        setSnapshot((prev) => ({
          ...prev,
          lastError:
            error instanceof Error && error.message
              ? error.message
              : "启动器初始化失败。",
          serviceDetail: "启动器初始化失败。",
        }));
      })
      .finally(() => {
        setBusyAction(null);
        setInitializing(false);
      });

    return unsub;
  }, []);

  useEffect(() => {
    window.rayleaLauncher.isMaximized().then(setIsMaximized);
    const unsub = window.rayleaLauncher.onMaximizedChange(setIsMaximized);
    return unsub;
  }, []);

  const describeError = useCallback((error: unknown, fallback: string) => {
    if (error instanceof Error && error.message) {
      return error.message;
    }
    return fallback;
  }, []);

  const runAction = useCallback(
    async (action: string, task: () => Promise<void>) => {
      setBusyAction(action);
      try {
        await task();
      } catch (error) {
        setSnapshot((prev) => ({
          ...prev,
          lastError: describeError(error, "启动器操作失败。"),
          serviceDetail:
            action === "restart"
              ? "重启服务失败。"
              : action === "start"
                ? "启动服务失败。"
                : prev.serviceDetail,
        }));
      } finally {
        setBusyAction(null);
      }
    },
    [describeError],
  );

  const handleUpdateSettings = useCallback(
    (partial: Partial<LauncherSettings>) => {
      if (!editingSettings) return;
      setEditingDraft((prev) => ({
        ...(prev ?? snapshot.settings),
        ...partial,
      }));
    },
    [editingSettings, snapshot.settings],
  );

  const handleSaveSettings = useCallback(async () => {
    if (!editingDraft) return;
    await runAction("save", async () => {
      await window.rayleaLauncher.saveSettings(editingDraft);
      setEditingSettings(false);
      setEditingDraft(null);
    });
  }, [runAction, editingDraft]);

  const handleBeginEdit = useCallback(() => {
    setEditingDraft({ ...snapshot.settings });
    setEditingSettings(true);
  }, [snapshot.settings]);

  const handleCancelEdit = useCallback(() => {
    setEditingSettings(false);
    setEditingDraft(null);
  }, []);

  const handlePrimaryServiceAction = useCallback(() => {
    if (snapshot.serviceState === "ready") {
      return runAction("restart", async () => {
        await window.rayleaLauncher.stop();
        await window.rayleaLauncher.start();
      });
    }
    return runAction("start", () => window.rayleaLauncher.start());
  }, [runAction, snapshot.serviceState]);

  return (
    <AppShell
      snapshot={snapshot}
      activeSection={activeSection}
      settingsDraft={settingsDraft}
      editingSettings={editingSettings}
      diagnosticsSummary={diagnosticsSummary}
      busyAction={busyAction}
      controlsDisabled={controlsDisabled}
      isMaximized={isMaximized}
      onNavigate={setActiveSection}
      onRefresh={() => runAction("refresh", () => window.rayleaLauncher.refresh())}
      onStart={handlePrimaryServiceAction}
      onStop={() => runAction("stop", () => window.rayleaLauncher.stop())}
      onOpenWeb={() => runAction("open-web", () => window.rayleaLauncher.openWebUi())}
      onOpenReleasePage={() =>
        runAction("open-release-page", () =>
          window.rayleaLauncher.openReleasePage(),
        )
      }
      onOpenLogs={() =>
        runAction("open-logs", () =>
          window.rayleaLauncher.openLogsDirectory(),
        )
      }
      onResetAdmin={() =>
        runAction("reset-admin", () =>
          window.rayleaLauncher.resetAdmin(),
        )
      }
      onBeginEdit={handleBeginEdit}
      onCancelEdit={handleCancelEdit}
      onSaveSettings={handleSaveSettings}
      onUpdateSettings={handleUpdateSettings}
      onChooseServer={() => {
        window.rayleaLauncher
          .chooseServerExecutable()
          .then((value: string | null) => {
            if (value) {
              const next = {
                ...(editingDraft ?? snapshot.settings),
                serverExecutablePath: value,
              };
              setEditingDraft(next);
            }
          });
      }}
      onChooseConfig={() => {
        window.rayleaLauncher
          .chooseConfigFile()
          .then((value: string | null) => {
            if (value) {
              const next = {
                ...(editingDraft ?? snapshot.settings),
                configPath: value,
              };
              setEditingDraft(next);
            }
          });
      }}
      onChooseWorkdir={() => {
        window.rayleaLauncher
          .chooseWorkdir()
          .then((value: string | null) => {
            if (value) {
              const next = {
                ...(editingDraft ?? snapshot.settings),
                workdir: value,
              };
              setEditingDraft(next);
            }
          });
      }}
      onExit={() => window.rayleaLauncher.exitApplication()}
    />
  );
}
