// launcher/src/renderer/src/AppShellServiceControl.vue
<script setup lang="ts">
import { CircleStopIcon, GlobeIcon, PlayIcon, RefreshCwIcon } from "@lucide/vue";
import type { LauncherPresentationState } from "@shared/launcher-presentation";
import { AnimatePresence, motion } from "motion-v";
import { computed, useId } from "vue";

import { serviceStateConfig, serviceStateGlyphs } from "./AppShell.shared";
import LauncherButton from "./LauncherButton.vue";
import { launcherMotion, useLauncherReducedMotion } from "./launcherMotion";
import StatusLens from "./StatusLens.vue";

const props = defineProps<{
  attention: {
    label: string;
    text: string;
    tone: "attention" | "warning" | "danger";
  } | null;
  busyLabel: string;
  canOpenWebUi: boolean;
  controlsDisabled: boolean;
  externalService: boolean;
  serviceDetail: string;
  serviceState: LauncherPresentationState;
  showRunningActions: boolean;
  startDisabled: boolean;
  stopDisabled: boolean;
  stopOpensWeb: boolean;
}>();
const emit = defineEmits<{
  openWeb: [];
  start: [];
  stop: [];
}>();

const noteId = useId();
const reducedMotion = useLauncherReducedMotion();
const stateConfig = computed(() => serviceStateConfig[props.serviceState]);
const tone = computed(() => stateConfig.value.tone);
const stateLabel = computed(() => stateConfig.value.label);
const primaryDisabled = computed(() => props.showRunningActions ? !props.canOpenWebUi || props.controlsDisabled : props.startDisabled);
const note = computed(() => props.busyLabel
  || (!props.showRunningActions
    ? "服务启动后可进入管理界面"
    : props.externalService
      ? "服务由其他进程启动，无法在启动器中重启"
      : ""));

// State text fades in as it replaces the previous copy. Assistive technology reads the plain copy beside it.
const copyMotion = computed(() => ({
  initial: { opacity: 0, y: 4 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -4, transition: { duration: reducedMotion.value ? 0 : 0.12, ease: launcherMotion.ease } },
  transition: { duration: reducedMotion.value ? 0 : launcherMotion.content / 1000, ease: launcherMotion.ease },
}));
</script>

<template>
  <section class="service-control" :data-tone="tone" aria-labelledby="service-control-title">
    <div class="service-control__summary">
      <div class="service-control__state" aria-live="polite">
        <StatusLens
          :tone="tone"
          :icon="serviceStateGlyphs[serviceState]"
          :icon-key="serviceState"
          :spinning="serviceState === 'starting' || serviceState === 'stopping'"
        />
        <div class="service-control__state-copy">
          <h2 id="service-control-title" class="service-control__state-value">
            <span class="visually-hidden">服务控制：{{ stateLabel }}</span>
            <span class="presence-stack" aria-hidden="true">
              <AnimatePresence :initial="false">
                <motion.span :key="stateLabel" v-bind="copyMotion">{{ stateLabel }}</motion.span>
              </AnimatePresence>
            </span>
          </h2>
          <p class="visually-hidden">{{ serviceDetail }}</p>
          <div class="presence-stack" aria-hidden="true">
            <AnimatePresence :initial="false">
              <motion.p :key="serviceDetail" class="service-control__detail" v-bind="copyMotion">{{ serviceDetail }}</motion.p>
            </AnimatePresence>
          </div>
        </div>
      </div>
      <div v-if="attention" class="attention-note" :data-severity="attention.tone">
        <span class="attention-note__label">{{ attention.label }}</span>
        <span>{{ attention.text }}</span>
      </div>
    </div>

    <div class="service-control__actions">
      <!-- A service started elsewhere can only be stopped from its own management console. -->
      <LauncherButton v-if="stopOpensWeb" :icon="GlobeIcon" :disabled="controlsDisabled || !canOpenWebUi" @click="emit('openWeb')">
        在管理界面停止
      </LauncherButton>
      <LauncherButton v-else class="launcher-button--danger" :icon="CircleStopIcon" :disabled="stopDisabled" @click="emit('stop')">
        停止服务
      </LauncherButton>
      <LauncherButton
        v-if="showRunningActions"
        :icon="RefreshCwIcon"
        :disabled="startDisabled"
        :aria-describedby="externalService ? noteId : undefined"
        @click="emit('start')"
      >
        重启服务
      </LauncherButton>
      <LauncherButton v-else :icon="GlobeIcon" disabled>管理界面</LauncherButton>
      <LauncherButton
        class="service-control__primary"
        :icon="showRunningActions ? GlobeIcon : PlayIcon"
        :emphasis="primaryDisabled ? 'regular' : 'prominent'"
        :disabled="primaryDisabled"
        @click="showRunningActions ? emit('openWeb') : emit('start')"
      >
        {{ showRunningActions ? "管理界面" : "启动服务" }}
      </LauncherButton>
      <p v-if="note" :id="noteId" class="operation-status" aria-live="polite">{{ note }}</p>
    </div>
  </section>
</template>

// launcher/src/renderer/src/AppShellServiceControl.tsx
import { Button } from "@fluentui/react-components";
import {
  ArrowSync20Regular,
  Globe20Regular,
  Play20Regular,
  Power24Filled,
  Stop20Regular,
} from "@fluentui/react-icons";
import type { LauncherPresentationState } from "@shared/launcher-presentation";
import { AnimatePresence, motion, useIsPresent } from "motion/react";
import { useId, type ReactNode } from "react";

import { serviceStateConfig, serviceStateGlyphs } from "./AppShell.shared";
import { launcherMotion, useLauncherReducedMotion } from "./launcherMotion";
import { StatusLens } from "./StatusLens";

type AppShellServiceControlProps = {
  attention: {
    label: string;
    text: string;
    tone: "attention" | "warning" | "danger";
  } | null;
  busyLabel: string;
  canOpenWebUi: boolean;
  controlsDisabled: boolean;
  externalService: boolean;
  onOpenWeb: () => void;
  onStart: () => void;
  onStop: () => void;
  primaryActionLabel: string;
  showRunningActions: boolean;
  snapshot: {
    serviceDetail: string;
    serviceState: LauncherPresentationState;
  };
  startDisabled: boolean;
  stopDisabled: boolean;
};

/** State text that fades in as it replaces the previous copy; the outgoing copy is hidden from assistive technology. */
function StateCopy({ as = "span", className, children }: { as?: "span" | "p"; className?: string; children: ReactNode }) {
  const isPresent = useIsPresent();
  const reducedMotion = useLauncherReducedMotion();
  const Element = as === "p" ? motion.p : motion.span;
  return (
    <Element
      className={className}
      aria-hidden={isPresent ? undefined : true}
      initial={{ opacity: 0, y: 4 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -4, transition: { duration: reducedMotion ? 0 : 0.12, ease: launcherMotion.ease } }}
      transition={{ duration: reducedMotion ? 0 : launcherMotion.content / 1000, ease: launcherMotion.ease }}
    >
      {children}
    </Element>
  );
}

export function AppShellServiceControl({
  attention,
  busyLabel,
  canOpenWebUi,
  controlsDisabled,
  externalService,
  onOpenWeb,
  onStart,
  onStop,
  primaryActionLabel,
  showRunningActions,
  snapshot,
  startDisabled,
  stopDisabled,
}: AppShellServiceControlProps) {
  const noteId = useId();
  const stateConfig = serviceStateConfig[snapshot.serviceState];
  const tone = stateConfig?.tone ?? "neutral";
  const stateLabel = stateConfig?.label ?? "未知";
  const primaryDisabled = showRunningActions ? !canOpenWebUi || controlsDisabled : startDisabled;
  const note = busyLabel
    || (!showRunningActions
      ? "服务启动后可进入管理界面"
      : externalService
        ? "服务由其他进程启动，无法在启动器中重启"
        : "");

  return (
    <section className="service-control" data-tone={tone} aria-labelledby="service-control-title">
      <div className="service-control__summary">
        <div className="service-control__state" aria-live="polite">
          <StatusLens
            tone={tone}
            icon={serviceStateGlyphs[snapshot.serviceState] ?? <Power24Filled />}
            iconKey={snapshot.serviceState}
            spinning={snapshot.serviceState === "starting" || snapshot.serviceState === "stopping"}
          />
          <div className="service-control__state-copy">
            <h2 id="service-control-title" className="service-control__state-value">
              <span className="visually-hidden">服务控制：</span>
              <span className="presence-stack">
                <AnimatePresence initial={false}>
                  <StateCopy key={stateLabel}>{stateLabel}</StateCopy>
                </AnimatePresence>
              </span>
            </h2>
            <div className="presence-stack">
              <AnimatePresence initial={false}>
                <StateCopy key={snapshot.serviceDetail} as="p" className="service-control__detail">{snapshot.serviceDetail}</StateCopy>
              </AnimatePresence>
            </div>
          </div>
        </div>
        {attention ? (
          <div className="attention-note" data-severity={attention.tone}>
            <span className="attention-note__label">{attention.label}</span>
            <span>{attention.text}</span>
          </div>
        ) : null}
      </div>

      <div className="service-control__actions">
        <Button appearance="secondary" className="launcher-button launcher-button--danger" data-emphasis="regular" onClick={onStop} disabled={stopDisabled} icon={<Stop20Regular />}>停止服务</Button>
        {showRunningActions ? (
          <Button
            appearance="secondary"
            className="launcher-button"
            data-emphasis="regular"
            onClick={onStart}
            disabled={startDisabled}
            aria-describedby={externalService ? noteId : undefined}
            icon={<ArrowSync20Regular />}
          >
            重启服务
          </Button>
        ) : (
          <Button appearance="secondary" className="launcher-button" data-emphasis="regular" onClick={onOpenWeb} disabled icon={<Globe20Regular />}>管理界面</Button>
        )}
        <Button
          appearance="primary"
          className="launcher-button service-control__primary"
          data-emphasis={primaryDisabled ? "regular" : "prominent"}
          onClick={showRunningActions ? onOpenWeb : onStart}
          disabled={primaryDisabled}
          icon={showRunningActions ? <Globe20Regular /> : <Play20Regular />}
        >
          {showRunningActions ? "管理界面" : primaryActionLabel}
        </Button>
        {note ? (
          <p id={noteId} className="operation-status" aria-live="polite">
            {note}
          </p>
        ) : null}
      </div>
    </section>
  );
}
