// launcher/src/renderer/src/AppShell.tsx
import { useMemo } from "react";
import {
  Radio,
  RadioGroup,
  Input,
  PresenceBadge,
  Text,
  Button,
} from "@fluentui/react-components";
import type { PresenceBadgeStatus } from "@fluentui/react-components";
import {
  Play20Filled,
  Stop20Filled,
  Globe20Filled,
  FolderOpen20Filled,
  CheckmarkCircle20Filled,
  Warning20Filled,
  DismissCircle20Filled,
  Status20Filled,
  HeartPulse20Filled,
  DocumentText20Filled,
  Settings20Filled,
  ArrowClockwise20Regular,
  Subtract20Regular,
  Square20Regular,
  SquareMultiple20Regular,
  Dismiss20Regular,
} from "@fluentui/react-icons";
import type {
  LauncherSettings,
  LauncherSnapshot,
  LauncherServiceState,
} from "@shared/launcher-models";

type SectionId = "status" | "environment" | "diagnostics" | "settings";

const serviceStateConfig: Record<
  LauncherServiceState,
  { status: PresenceBadgeStatus; label: string }
> = {
  stopped: { status: "offline", label: "已停止" },
  starting: { status: "busy", label: "启动中" },
  external_service: { status: "available", label: "运行中" },
  ready: { status: "available", label: "运行中" },
  degraded: { status: "busy", label: "受限运行" },
  setup_required: { status: "blocked", label: "需要设置" },
  shutting_down: { status: "busy", label: "停止中" },
  failed: { status: "blocked", label: "启动失败" },
};

const severityConfig = {
  error: { color: "danger" as const, label: "阻塞", icon: <DismissCircle20Filled /> },
  warning: { color: "warning" as const, label: "警告", icon: <Warning20Filled /> },
  ok: { color: "success" as const, label: "正常", icon: <CheckmarkCircle20Filled /> },
};

type AppShellProps = {
  snapshot: LauncherSnapshot;
  activeSection: SectionId;
  settingsDraft: LauncherSettings;
  editingSettings: boolean;
  diagnosticsSummary: string;
  busyAction: string | null;
  controlsDisabled: boolean;
  isMaximized: boolean;
  onNavigate: (section: SectionId) => void;
  onRefresh: () => void;
  onStart: () => void;
  onStop: () => void;
  onOpenWeb: () => void;
  onOpenReleasePage: () => void;
  onOpenLogs: () => void;
  onBeginEdit: () => void;
  onCancelEdit: () => void;
  onSaveSettings: () => void;
  onUpdateSettings: (partial: Partial<LauncherSettings>) => void;
  onChooseServer: () => void;
  onChooseConfig: () => void;
  onChooseWorkdir: () => void;
  onExit: () => void;
};

const sections = [
  { id: "status" as SectionId, title: "运行状态", icon: <Status20Filled /> },
  { id: "environment" as SectionId, title: "环境检查", icon: <HeartPulse20Filled /> },
  { id: "diagnostics" as SectionId, title: "日志诊断", icon: <DocumentText20Filled /> },
  { id: "settings" as SectionId, title: "偏好设置", icon: <Settings20Filled /> },
];

const closeBehaviorOptions: Array<{
  value: LauncherSettings["closeBehavior"];
  label: string;
}> = [
  { value: "ask_every_time", label: "每次询问" },
  { value: "hide_to_tray", label: "系统托盘" },
  { value: "exit_application", label: "完全退出" },
];

function statusSummary(state: LauncherServiceState): string {
  switch (state) {
    case "stopped": return "已停止";
    case "starting": return "正在启动";
    case "external_service":
    case "ready": return "正在运行";
    case "degraded": return "受限运行";
    case "setup_required": return "需要设置";
    case "shutting_down": return "正在停止";
    case "failed": return "启动失败";
    default: return "未知状态";
  }
}

export function AppShell({
  snapshot,
  activeSection,
  settingsDraft,
  editingSettings,
  diagnosticsSummary,
  busyAction,
  controlsDisabled,
  isMaximized,
  onNavigate,
  onRefresh,
  onStart,
  onStop,
  onOpenWeb,
  onOpenReleasePage,
  onOpenLogs,
  onBeginEdit,
  onCancelEdit,
  onSaveSettings,
  onUpdateSettings,
  onChooseServer,
  onChooseConfig,
  onChooseWorkdir,
  onExit,
}: AppShellProps) {
  const groupedChecks = useMemo(() => ({
    blocking: snapshot.environmentChecks.filter(i => i.severity === "error"),
    warnings: snapshot.environmentChecks.filter(i => i.severity === "warning"),
    ready: snapshot.environmentChecks.filter(i => i.severity === "ok"),
  }), [snapshot.environmentChecks]);

  const trayStatus = useMemo(() => statusSummary(snapshot.serviceState), [snapshot.serviceState]);
  const startDisabled =
    controlsDisabled ||
    busyAction === "start" ||
    busyAction === "restart" ||
    busyAction === "stop";
  const stopDisabled = controlsDisabled || busyAction === "restart" || busyAction === "stop";

  return (
    <div className="app-shell">
      <div className="window-drag-handle">
        <div className="window-title">
          RAYLEALAUNCHER
        </div>
        <div className="window-controls">
          <button className="window-control-btn" onClick={() => window.rayleaLauncher.minimize()} title="最小化"><Subtract20Regular /></button>
          <button className="window-control-btn" onClick={() => window.rayleaLauncher.maximize()} title={isMaximized ? "还原" : "最大化"}>{isMaximized ? <SquareMultiple20Regular /> : <Square20Regular />}</button>
          <button className="window-control-btn danger" onClick={() => window.rayleaLauncher.close()} title="关闭"><Dismiss20Regular /></button>
        </div>
      </div>

      <aside className="shell-sidebar">
        <div className="brand-card glass-panel">
          <div className="brand-eyebrow">RayleaBot</div>
          <div className="brand-headline">
            <h1>RayleaLauncher</h1>
            {snapshot.releaseCheck.currentVersion && (
              <span className="glass-chip">
                v{snapshot.releaseCheck.currentVersion}
              </span>
            )}
          </div>
        </div>

        <nav className="section-nav">
          {sections.map((section) => (
            <button
              key={section.id}
              className={`nav-item${activeSection === section.id ? " active" : ""}`}
              onClick={() => onNavigate(section.id)}
            >
              <span className="nav-item__icon">{section.icon}</span>
              <span className="nav-item__label">{section.title}</span>
            </button>
          ))}
        </nav>

        <div className="sidebar-footer glass-panel glass-panel--subtle">
          <div className="sidebar-footer__group">
            <Text size={100} className="eyebrow-text">LAUNCHER STATUS</Text>
            <Text weight="bold" className="sidebar-footer__status">{trayStatus.toUpperCase()}</Text>
          </div>
          <div className="sidebar-footer__group">
            <Text size={100} className="eyebrow-text">API ENDPOINT</Text>
            <Text size={100} className="sidebar-footer__endpoint">{snapshot.endpoint.baseUrl}</Text>
          </div>
          <Button
            appearance="transparent"
            size="small"
            onClick={onRefresh}
            icon={<ArrowClockwise20Regular />}
            className="frost-button frost-button--ghost frost-button--inline"
          >
            刷新状态
          </Button>
        </div>
      </aside>

      <main className="shell-main">
        {/* Service Control (只在运行状态显示) */}
        {activeSection === "status" && (
          <section className="hero-card glass-panel">
            <div className="hero-copy">
              <div className="brand-eyebrow">Service Control</div>
              <div className="hero-status-row">
                <PresenceBadge status={serviceStateConfig[snapshot.serviceState]?.status ?? "unknown"} size="large" />
                <Text weight="bold" size={500} className="hero-status-text">{serviceStateConfig[snapshot.serviceState]?.label ?? "未知"}</Text>
              </div>
              <Text size={200} className="hero-detail">{snapshot.serviceDetail}</Text>
              {snapshot.lastError && (
                <div className="inline-alert inline-alert--error">
                  <span className="inline-alert__icon"><DismissCircle20Filled /></span>
                  <span className="inline-alert__text">{snapshot.lastError}</span>
                </div>
              )}
            </div>
            <div className="hero-actions">
              <Button
                appearance="transparent"
                className="frost-button frost-button--primary frost-button--block"
                onClick={onStart}
                disabled={startDisabled}
                icon={<Play20Filled />}
              >
                {snapshot.serviceState === "ready" ? "重启服务" : "启动 RayleaBot"}
              </Button>
              <Button
                appearance="transparent"
                className="frost-button frost-button--secondary frost-button--block"
                onClick={onStop}
                disabled={stopDisabled}
                icon={<Stop20Filled />}
              >
                停止服务
              </Button>
              <Button
                appearance="transparent"
                className="frost-button frost-button--secondary frost-button--block"
                onClick={onOpenWeb}
                disabled={controlsDisabled}
                icon={<Globe20Filled />}
              >
                管理面板
              </Button>
            </div>
          </section>
        )}

        {/* 统一的环境检查项 (首页与详情页共享样式) */}
        {(activeSection === "status" || activeSection === "environment") && snapshot.environmentChecks.length > 0 && (
          <div className="checks-stack">
            {snapshot.environmentChecks.map(item => (
              (activeSection === "environment" || item.severity !== "ok") && (
                <div key={item.code} className={`check-item glass-panel glass-panel--subtle check-item--${item.severity}`}>
                  <div className="check-item__lead">
                    <div className="check-item__icon">
                      {severityConfig[item.severity as keyof typeof severityConfig]?.icon}
                    </div>
                    <div className="check-item__copy">
                      <Text weight="bold" size={300}>{item.title}</Text>
                      <Text size={200} className="check-item__summary">
                        {item.code === "os.long_paths_unknown" && item.severity === "warning"
                          ? "无法确认长路径支持状态。若资源展开遇到限制，请手动检查系统长路径设置。" 
                          : item.summary}
                      </Text>
                    </div>
                  </div>
                  <span className={`status-pill status-pill--${item.severity}`}>
                    {severityConfig[item.severity as keyof typeof severityConfig]?.label}
                  </span>
                </div>
              )
            ))}
          </div>
        )}

        {activeSection === "status" && (
          <>
            <article className="panel glass-panel">
              <div className="brand-eyebrow">核心参数</div>
              <div className="status-list">
                <div className="status-item"><span className="status-label">进程 ID</span><code className="status-value">{snapshot.processId ?? "—"}</code></div>
                <div className="status-item"><span className="status-label">本地端点</span><span className="status-value mono">{snapshot.endpoint.baseUrl}</span></div>
                <div className="status-item"><span className="status-label">工作目录</span><span className="status-value mono">{snapshot.settings.workdir}</span></div>
              </div>
            </article>

            <article className="panel glass-panel glass-panel--subtle panel-row">
              <div className="panel-copy">
                <div className="brand-eyebrow brand-eyebrow--tight">版本监控</div>
                <Text size={200} className="panel-muted">{snapshot.releaseCheck.summary}</Text>
              </div>
              <Button
                appearance="transparent"
                size="small"
                className="frost-button frost-button--secondary"
                onClick={onOpenReleasePage}
              >
                检查更新
              </Button>
            </article>

            <article className="panel glass-panel">
              <div className="brand-eyebrow">异常输出监控</div>
              <pre className="log-surface">
                {snapshot.recentStderr.join("\n") || "当前无异常日志。"}
              </pre>
              <Button
                appearance="transparent"
                size="small"
                className="frost-button frost-button--ghost"
                onClick={onOpenLogs}
                icon={<FolderOpen20Filled />}
              >
                查看完整日志
              </Button>
            </article>
          </>
        )}

        {activeSection === "environment" && (
          <article className="panel glass-panel metric-panel">
            <div className="brand-eyebrow">环境评分</div>
            <div className="metric-grid">
              <div className="metric-card metric-card--error"><Text size={100} block className="metric-label">阻塞项</Text><Text size={600} weight="bold">{groupedChecks.blocking.length}</Text></div>
              <div className="metric-card metric-card--warning"><Text size={100} block className="metric-label">警告项</Text><Text size={600} weight="bold">{groupedChecks.warnings.length}</Text></div>
              <div className="metric-card metric-card--ok"><Text size={100} block className="metric-label">正常项</Text><Text size={600} weight="bold">{groupedChecks.ready.length}</Text></div>
            </div>
          </article>
        )}

        {activeSection === "diagnostics" && (
          <article className="panel glass-panel diagnostics-panel">
            <div className="brand-eyebrow">系统诊断快照</div>
            <pre className="log-surface diagnostics-surface">
              {diagnosticsSummary}
            </pre>
          </article>
        )}

        {activeSection === "settings" && (
          <article className="panel glass-panel settings-panel">
            <div className="panel-toolbar">
              <div className="panel-copy">
                <div className="brand-eyebrow brand-eyebrow--tight">路径配置</div>
                {editingSettings && <span className="glass-chip glass-chip--accent">编辑中</span>}
              </div>
              <div className="settings-actions">
                {!editingSettings ? (
                  <Button
                    appearance="transparent"
                    size="small"
                    className="frost-button frost-button--primary"
                    onClick={onBeginEdit}
                  >
                    编辑配置
                  </Button>
                ) : (
                  <>
                    <Button
                      appearance="transparent"
                      size="small"
                      className="frost-button frost-button--ghost"
                      onClick={onCancelEdit}
                    >
                      放弃
                    </Button>
                    <Button
                      appearance="transparent"
                      size="small"
                      className="frost-button frost-button--primary"
                      onClick={onSaveSettings}
                    >
                      保存
                    </Button>
                  </>
                )}
              </div>
            </div>

            <div className="settings-shell">
              <div className="path-stack">
                <label className="path-field">
                  <span className="path-field__label">服务端可执行文件路径</span>
                  <div className="path-control">
                    <Input
                      value={settingsDraft.serverExecutablePath}
                      readOnly={!editingSettings}
                      className="frost-input frost-input--path"
                      onChange={(_, d) => onUpdateSettings({ serverExecutablePath: d.value })}
                    />
                    <Button
                      appearance="transparent"
                      disabled={!editingSettings}
                      size="small"
                      className="frost-button frost-button--secondary frost-button--compact"
                      onClick={onChooseServer}
                      icon={<FolderOpen20Filled />}
                    >
                      浏览
                    </Button>
                  </div>
                </label>

                <label className="path-field">
                  <span className="path-field__label">配置文件路径</span>
                  <div className="path-control">
                    <Input
                      value={settingsDraft.configPath}
                      readOnly={!editingSettings}
                      className="frost-input frost-input--path"
                      onChange={(_, d) => onUpdateSettings({ configPath: d.value })}
                    />
                    <Button
                      appearance="transparent"
                      disabled={!editingSettings}
                      size="small"
                      className="frost-button frost-button--secondary frost-button--compact"
                      onClick={onChooseConfig}
                      icon={<FolderOpen20Filled />}
                    >
                      浏览
                    </Button>
                  </div>
                </label>

                <label className="path-field">
                  <span className="path-field__label">工作目录</span>
                  <div className="path-control">
                    <Input
                      value={settingsDraft.workdir}
                      readOnly={!editingSettings}
                      className="frost-input frost-input--path"
                      onChange={(_, d) => onUpdateSettings({ workdir: d.value })}
                    />
                    <Button
                      appearance="transparent"
                      disabled={!editingSettings}
                      size="small"
                      className="frost-button frost-button--secondary frost-button--compact"
                      onClick={onChooseWorkdir}
                      icon={<FolderOpen20Filled />}
                    >
                      选择
                    </Button>
                  </div>
                </label>
              </div>

              <section className="preferences-panel glass-panel glass-panel--subtle">
                <div className="brand-eyebrow brand-eyebrow--tight">退出行为偏好</div>
                <RadioGroup
                  value={settingsDraft.closeBehavior}
                  onChange={(_, d) => onUpdateSettings({ closeBehavior: d.value as LauncherSettings["closeBehavior"] })}
                >
                  <div className="preference-options">
                    {closeBehaviorOptions.map((option) => (
                      <div
                        key={option.value}
                        className={`preference-option${settingsDraft.closeBehavior === option.value ? " is-selected" : ""}${!editingSettings ? " is-disabled" : ""}`}
                      >
                        <Radio
                          className="preference-radio"
                          label={option.label}
                          value={option.value}
                          disabled={!editingSettings}
                        />
                      </div>
                    ))}
                  </div>
                </RadioGroup>
              </section>
            </div>

            <div className="settings-exit-row">
              <Button
                appearance="transparent"
                size="small"
                className="frost-button frost-button--danger"
                onClick={onExit}
                icon={<Stop20Filled />}
              >
                退出 RayleaLauncher
              </Button>
            </div>
          </article>
        )}
      </main>
    </div>
  );
}

// launcher/src/renderer/src/AppShell.vue
<script setup lang="ts">
import { computed } from "vue";
import type { LauncherSettings, LauncherSnapshot, LauncherServiceState } from "@shared/launcher-models";

type SectionId = "status" | "environment" | "diagnostics" | "settings";

const props = withDefaults(
  defineProps<{
    snapshot: LauncherSnapshot;
    activeSection: SectionId;
    settingsDraft?: LauncherSettings;
    editingSettings?: boolean;
    diagnosticsSummary?: string;
    busyAction?: string | null;
    controlsDisabled?: boolean;
  }>(),
  {
    settingsDraft: undefined,
    editingSettings: false,
    diagnosticsSummary: "",
    busyAction: null,
    controlsDisabled: false,
  },
);

const emit = defineEmits<{
  navigate: [SectionId];
  refresh: [];
  start: [];
  stop: [];
  openWeb: [];
  openReleasePage: [];
  openLogs: [];
  beginEdit: [];
  cancelEdit: [];
  saveSettings: [];
  updateSettings: [LauncherSettings];
  chooseServer: [];
  chooseConfig: [];
  chooseWorkdir: [];
  exit: [];
}>();

const sections = [
  { id: "status", title: "状态" },
  { id: "environment", title: "环境检查" },
  { id: "diagnostics", title: "日志与诊断" },
  { id: "settings", title: "设置" },
] as const satisfies ReadonlyArray<{ id: SectionId; title: string }>;

const severityRank: Record<string, number> = { error: 0, warning: 1, ok: 2 };

const primaryIssue = computed(() => {
  return [...props.snapshot.environmentChecks].sort((left, right) => severityRank[left.severity] - severityRank[right.severity])[0];
});

const groupedChecks = computed(() => {
  return {
    blocking: props.snapshot.environmentChecks.filter((item) => item.severity === "error"),
    warnings: props.snapshot.environmentChecks.filter((item) => item.severity === "warning"),
    ready: props.snapshot.environmentChecks.filter((item) => item.severity === "ok"),
  };
});

const trayStatus = computed(() => statusSummary(props.snapshot.serviceState));

function statusSummary(state: LauncherServiceState) {
  switch (state) {
    case "stopped":
      return "未启动";
    case "starting":
      return "启动中";
    case "external_service":
    case "ready":
      return "运行中";
    case "degraded":
      return "受限运行";
    case "setup_required":
      return "需要设置";
    case "shutting_down":
      return "停止中";
    case "failed":
      return "启动失败";
    default:
      return "未知状态";
  }
}

function updateDraft(partial: Partial<LauncherSettings>) {
  emit("updateSettings", {
    ...(props.settingsDraft ?? props.snapshot.settings),
    ...partial,
  });
}
</script>

<template>
  <div class="app-shell">
    <aside class="shell-sidebar">
      <div class="brand-card">
        <div class="brand-eyebrow">RayleaBot</div>
        <h1>RayleaBot 启动器</h1>
        <p>本地服务壳、环境检查和管理入口。</p>
      </div>

      <nav class="section-nav" aria-label="Primary">
        <button
          v-for="section in sections"
          :key="section.id"
          class="nav-item"
          :class="{ active: activeSection === section.id }"
          type="button"
          @click="emit('navigate', section.id)"
        >
          {{ section.title }}
        </button>
      </nav>

      <div class="sidebar-summary">
        <span>当前状态</span>
        <strong>{{ trayStatus }}</strong>
      </div>
      <div class="sidebar-summary subtle">
        <span>服务入口</span>
        <strong>{{ snapshot.endpoint.baseUrl }}</strong>
      </div>
    </aside>

    <main class="shell-main">
      <section class="hero-card">
        <div class="hero-copy">
          <div class="hero-eyebrow">Service Control</div>
          <h2>{{ snapshot.serviceDetail }}</h2>
          <p>{{ snapshot.lastError || "查看当前状态、主操作和需要处理的问题。" }}</p>
        </div>
        <div class="hero-actions">
          <button class="action primary" type="button" :disabled="controlsDisabled || busyAction === 'start'" @click="emit('start')">
            {{ snapshot.serviceState === 'external_service' || snapshot.serviceState === 'ready' ? '重新检查' : '启动服务' }}
          </button>
          <button class="action" type="button" :disabled="controlsDisabled || busyAction === 'stop'" @click="emit('stop')">停止服务</button>
          <button class="action" type="button" :disabled="controlsDisabled" @click="emit('openWeb')">打开管理界面</button>
          <button class="action ghost" type="button" :disabled="controlsDisabled" @click="emit('refresh')">刷新状态</button>
        </div>
      </section>

      <section v-if="primaryIssue" class="issue-banner" :class="primaryIssue.severity">
        <div>
          <strong>{{ primaryIssue.title }}</strong>
          <p>{{ primaryIssue.summary }}</p>
        </div>
        <p>{{ primaryIssue.remediation || primaryIssue.detail }}</p>
      </section>

      <section v-if="activeSection === 'status'" class="content-grid">
        <article class="panel panel-primary">
          <h3>服务信息</h3>
          <dl class="kv-grid">
            <div><dt>状态</dt><dd>{{ trayStatus }}</dd></div>
            <div><dt>服务入口</dt><dd>{{ snapshot.endpoint.baseUrl }}</dd></div>
            <div><dt>工作目录</dt><dd>{{ snapshot.settings.workdir }}</dd></div>
            <div><dt>PID</dt><dd>{{ snapshot.processId ?? '—' }}</dd></div>
          </dl>
        </article>

        <article class="panel">
          <h3>版本与发布</h3>
          <p>{{ snapshot.releaseCheck.summary }}</p>
          <button class="action ghost" type="button" @click="emit('openReleasePage')">打开发布页</button>
        </article>

        <article class="panel full">
          <h3>最近错误输出</h3>
          <pre class="log-surface">{{ snapshot.recentStderr.join('\n') || '当前没有新的错误。' }}</pre>
          <button class="action ghost" type="button" @click="emit('openLogs')">打开日志目录</button>
        </article>
      </section>

      <section v-else-if="activeSection === 'environment'" class="content-grid">
        <article class="panel metric-panel">
          <div class="metric"><span>阻塞项</span><strong>{{ groupedChecks.blocking.length }}</strong></div>
          <div class="metric"><span>需注意</span><strong>{{ groupedChecks.warnings.length }}</strong></div>
          <div class="metric"><span>正常项</span><strong>{{ groupedChecks.ready.length }}</strong></div>
        </article>

        <article class="panel full">
          <h3>环境检查结果</h3>
          <ul class="check-list">
            <li v-for="item in snapshot.environmentChecks" :key="item.code" :class="item.severity">
              <div>
                <strong>{{ item.title }}</strong>
                <p>{{ item.summary }}</p>
              </div>
              <p>{{ item.detail }} {{ item.remediation }}</p>
            </li>
          </ul>
        </article>
      </section>

      <section v-else-if="activeSection === 'diagnostics'" class="content-grid">
        <article class="panel full">
          <h3>诊断摘要</h3>
          <pre class="log-surface">{{ diagnosticsSummary }}</pre>
        </article>
      </section>

      <section v-else class="content-grid">
        <article class="panel full">
          <div class="settings-header">
            <div>
              <h3>本地设置</h3>
              <p>管理本地路径和关闭策略。</p>
            </div>
            <div class="settings-actions">
              <button v-if="!editingSettings" class="action ghost" type="button" :disabled="controlsDisabled" @click="emit('beginEdit')">编辑路径</button>
              <template v-else>
                <button class="action ghost" type="button" :disabled="controlsDisabled" @click="emit('cancelEdit')">取消编辑</button>
                <button class="action primary" type="button" :disabled="controlsDisabled" @click="emit('saveSettings')">保存设置</button>
              </template>
            </div>
          </div>

          <div class="settings-grid">
            <label class="field">
              <span>服务端可执行文件</span>
              <div class="field-inline">
                <input :value="(settingsDraft ?? snapshot.settings).serverExecutablePath" :readonly="!editingSettings" @input="updateDraft({ serverExecutablePath: ($event.target as HTMLInputElement).value })" />
                <button class="action ghost" type="button" :disabled="!editingSettings" @click="emit('chooseServer')">浏览</button>
              </div>
            </label>

            <label class="field">
              <span>用户配置文件</span>
              <div class="field-inline">
                <input :value="(settingsDraft ?? snapshot.settings).configPath" :readonly="!editingSettings" @input="updateDraft({ configPath: ($event.target as HTMLInputElement).value })" />
                <button class="action ghost" type="button" :disabled="!editingSettings" @click="emit('chooseConfig')">浏览</button>
              </div>
            </label>

            <label class="field">
              <span>工作目录</span>
              <div class="field-inline">
                <input :value="(settingsDraft ?? snapshot.settings).workdir" :readonly="!editingSettings" @input="updateDraft({ workdir: ($event.target as HTMLInputElement).value })" />
                <button class="action ghost" type="button" :disabled="!editingSettings" @click="emit('chooseWorkdir')">选择目录</button>
              </div>
            </label>
          </div>

          <div class="close-behavior">
            <label>
              <input
                type="radio"
                name="close-behavior"
                value="ask_every_time"
                :checked="(settingsDraft ?? snapshot.settings).closeBehavior === 'ask_every_time'"
                :disabled="!editingSettings"
                @change="updateDraft({ closeBehavior: 'ask_every_time' })"
              />
              每次询问
            </label>
            <label>
              <input
                type="radio"
                name="close-behavior"
                value="hide_to_tray"
                :checked="(settingsDraft ?? snapshot.settings).closeBehavior === 'hide_to_tray'"
                :disabled="!editingSettings"
                @change="updateDraft({ closeBehavior: 'hide_to_tray' })"
              />
              隐藏到托盘
            </label>
            <label>
              <input
                type="radio"
                name="close-behavior"
                value="exit_application"
                :checked="(settingsDraft ?? snapshot.settings).closeBehavior === 'exit_application'"
                :disabled="!editingSettings"
                @change="updateDraft({ closeBehavior: 'exit_application' })"
              />
              完全退出
            </label>
          </div>

          <button class="action danger" type="button" @click="emit('exit')">完全退出启动器</button>
        </article>
      </section>
    </main>
  </div>
</template>
