// launcher/src/renderer/src/LauncherDialog.vue
<script setup lang="ts">
import { DialogContent, DialogOverlay, DialogPortal, DialogRoot } from "reka-ui";
import { motion } from "motion-v";
import { computed, ref, watch } from "vue";

import { overlayEnter, overlayExit, useLauncherReducedMotion } from "./launcherMotion";

const props = defineProps<{
  open: boolean;
  tone?: "danger" | "attention";
}>();
const emit = defineEmits<{ dismiss: [] }>();

// The dialog, its content and its focus trap stay mounted until the exit animation ends, so the surface does
// not vanish mid-fade.
const present = ref(props.open);
watch(() => props.open, (open) => {
  if (open) present.value = true;
});

const reducedMotion = useLauncherReducedMotion();
const transition = computed(() => reducedMotion.value ? { duration: 0 } : props.open ? overlayEnter : overlayExit);

function dismiss() {
  if (props.open) emit("dismiss");
}

function finishExit() {
  if (!props.open) present.value = false;
}
</script>

<!-- A Reka dialog whose surface and scrim are animated by Motion. -->
<template>
  <DialogRoot :open="present" @update:open="dismiss">
    <DialogPortal force-mount>
      <DialogOverlay v-if="present" force-mount as-child>
        <motion.div
          class="launcher-dialog-scrim"
          :initial="reducedMotion ? false : { opacity: 0 }"
          :animate="{ opacity: open ? 1 : 0 }"
          :transition="transition"
        />
      </DialogOverlay>
      <DialogContent
        v-if="present"
        force-mount
        as-child
        @escape-key-down.prevent="dismiss"
        @pointer-down-outside.prevent="dismiss"
        @interact-outside.prevent
      >
        <motion.section
          class="launcher-dialog"
          :data-tone="tone"
          :data-state="open ? 'open' : 'closing'"
          :initial="reducedMotion ? false : { opacity: 0, scale: 0.96 }"
          :animate="open ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.96 }"
          :transition="transition"
          @animation-complete="finishExit"
        >
          <slot />
        </motion.section>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// launcher/src/renderer/src/LauncherDialog.tsx
import { Dialog, DialogSurface } from "@fluentui/react-components";
import { motion, type HTMLMotionProps } from "motion/react";
import type { ElementType, HTMLAttributes, ReactNode } from "react";

import { overlayEnter, overlayExit, useExitPresence, useLauncherReducedMotion } from "./launcherMotion";

const MotionDialogSurface = motion.create(DialogSurface);

type LauncherDialogProps = {
  open: boolean;
  onDismiss: () => void;
  tone?: "danger" | "attention";
  children: ReactNode;
};

/**
 * A Fluent dialog whose surface and scrim are animated by Motion. The dialog, its content and its focus trap
 * stay mounted until the exit animation ends, so the surface does not vanish mid-fade.
 */
export function LauncherDialog({ open, onDismiss, tone, children }: LauncherDialogProps) {
  const [present, finishExit] = useExitPresence(open);
  const reducedMotion = useLauncherReducedMotion();
  const transition = reducedMotion ? { duration: 0 } : open ? overlayEnter : overlayExit;

  return (
    <Dialog
      open={present}
      surfaceMotion={null}
      onOpenChange={(_event, data) => {
        if (!data.open) onDismiss();
      }}
    >
      <MotionDialogSurface
        className="launcher-dialog"
        data-tone={tone}
        data-state={open ? "open" : "closing"}
        backdropMotion={null}
        backdrop={{
          children: (_Component: ElementType, props: HTMLAttributes<HTMLDivElement>) => (
            <motion.div
              {...(props as HTMLMotionProps<"div">)}
              initial={reducedMotion ? false : { opacity: 0 }}
              animate={{ opacity: open ? 1 : 0 }}
              transition={transition}
            />
          ),
        }}
        initial={reducedMotion ? false : { opacity: 0, scale: 0.96 }}
        animate={open ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.96 }}
        transition={transition}
        onAnimationComplete={finishExit}
      >
        {children}
      </MotionDialogSurface>
    </Dialog>
  );
}
